import requests

cookies = {
    "WMONID": "-KOnLSWUP26",
    "gubun": "on",
    "userid": "785701",
    "JSESSIONID": "1C0AD5D80D7FF12C373DD7C7B752015C",
}

headers = {
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
    "Accept-Language": "en,ru;q=0.9,en-CA;q=0.8,la;q=0.7,fr;q=0.6,ko;q=0.5",
    "Cache-Control": "max-age=0",
    "Connection": "keep-alive",
    "Content-Type": "application/x-www-form-urlencoded",
    "Origin": "https://www.autohubauction.co.kr",
    "Referer": "https://www.autohubauction.co.kr/newfront/receive/rc/receive_rc_list.do",
    "Sec-Fetch-Dest": "document",
    "Sec-Fetch-Mode": "navigate",
    "Sec-Fetch-Site": "same-origin",
    "Sec-Fetch-User": "?1",
    "Upgrade-Insecure-Requests": "1",
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36",
    "sec-ch-ua": '"Google Chrome";v="137", "Chromium";v="137", "Not/A)Brand";v="24"',
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": '"macOS"',
    # 'Cookie': 'WMONID=-KOnLSWUP26; gubun=on; userid=785701; JSESSIONID=1C0AD5D80D7FF12C373DD7C7B752015C',
}

data = {
    "i_iNowPageNo": "1",
    "i_sReturnUrl": "/newfront/receive/rc/receive_rc_list.do",
    "i_sReturnParam": "",
    "i_sActionFlag": "",
    "i_sReceiveCd": "",
    "pageFlag": "Y",
    "i_sAucNo": "1329",
    "i_sStartDt": "2025-06-18",
    "i_sAucTitle": "안성 2025/06/18 1329회차 경매",
    "i_sAucCode": "AC202506110001",
    "i_sSortFlag": "entry",
    "i_sMainModel": "",
    "i_sMakerCodeD": "",
    "i_sCarName1CodeD": "",
    "tabActiveIdx": "",
    "listTabActiveIdx": "",
    "receivecd": "RC202506130039",
    "i_sAucNoTempStr": "",
    "i_sMakerCodeD1": "",
    "i_sCarName1CodeD1": "",
    "i_sAucNoTemp1": "1329@@2025-06-18@@AC202506110001",
    "i_entryNoYn": "ALL",
    "i_parkingNoYn": "Y",
    "noSelect": "E",
    "i_sNo": "",
    "i_sMakerCode": "",
    "i_sCarName1Code": "",
    "i_sCarName2Code": "",
    "i_sCarName3Code": "",
    "i_sFueltypecode": "",
    "i_bojeongYn": "ALL",
    "i_sCarYearStr": "",
    "i_sCarYearEnd": "",
    "i_sDriveKmShortDescStr": "",
    "i_sDriveKmShortDescEnd": "",
    "i_sPricecStr": "",
    "i_sPricecEnd": "",
    "i_sAucResult": "",
    "i_sAucLane": "",
    "i_sEntryNo": "",
    "i_sParkingNo": "",
    "i_entryNoYn0": "ALL",
    "i_parkingNoYn0": "Y",
    "i_sAucNoTemp2": "1329@@2025-06-18@@AC202506110001",
    "i_sohYn": "ALL",
    "entrySort": "entry",
    "i_iPageSize": "10",
}

response = requests.post(
    "https://www.autohubauction.co.kr/newfront/onlineAuc/on/onlineAuc_on_detail.do",
    cookies=cookies,
    headers=headers,
    data=data,
)
