import requests

cookies = {
    "WMONID": "-KOnLSWUP26",
    "gubun": "on",
    "userid": "785701",
    "JSESSIONID": "7EA6DBDF17F5363E84E75496C90BF860",
    "notToday_PU202506260001": "Y",
}

headers = {
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
    "Accept-Language": "en,ru;q=0.9,en-CA;q=0.8,la;q=0.7,fr;q=0.6,ko;q=0.5",
    "Cache-Control": "max-age=0",
    "Connection": "keep-alive",
    "Content-Type": "application/x-www-form-urlencoded",
    "Origin": "https://www.autohubauction.co.kr",
    "Referer": "https://www.autohubauction.co.kr/newfront/receive/rc/receive_rc_list.do",
    "Sec-Fetch-Dest": "document",
    "Sec-Fetch-Mode": "navigate",
    "Sec-Fetch-Site": "same-origin",
    "Sec-Fetch-User": "?1",
    "Upgrade-Insecure-Requests": "1",
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36",
    "sec-ch-ua": '"Not)A;Brand";v="8", "Chromium";v="138", "Google Chrome";v="138"',
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": '"macOS"',
    # 'Cookie': 'WMONID=-KOnLSWUP26; gubun=on; userid=785701; JSESSIONID=7EA6DBDF17F5363E84E75496C90BF860; notToday_PU202506260001=Y',
}

data = {
    "i_iNowPageNo": "1",
    "i_sReturnUrl": "/newfront/receive/rc/receive_rc_list.do",
    "i_sReturnParam": "",
    "i_sActionFlag": "",
    "i_sReceiveCd": "",
    "pageFlag": "Y",
    "i_sAucNo": "1333",
    "i_sStartDt": "2025-07-16",
    "i_sAucTitle": "안성 2025/07/16 1333회차 경매",
    "i_sAucCode": "AC202507090001",
    "i_sSortFlag": "entry",
    "i_sMainModel": "",
    "i_sMakerCodeD": "",
    "i_sCarName1CodeD": "",
    "tabActiveIdx": "2",
    "listTabActiveIdx": "1",
    "receivecd": "",
    "i_sAucNoTempStr": "안성 2025/07/16 1333회차 경매",
    "i_sMakerCodeD1": "",
    "i_sCarName1CodeD1": "",
    "i_entryNoYn": "ALL",
    "i_parkingNoYn": "Y",
    "noSelect": "E",
    "i_sNo": "",
    "i_sMakerCode": "HD",
    "i_sCarName1Code": "HD03",
    "i_sCarName2Code": "013",
    "i_sCarName3Code": "002",
    "i_sFueltypecode": "01",
    "i_bojeongYn": "ALL",
    "i_sCarYearStr": "1993",
    "i_sCarYearEnd": "2023",
    "i_sDriveKmShortDescStr": "500",
    "i_sDriveKmShortDescEnd": "300000",
    "i_sPricecStr": "100",
    "i_sPricecEnd": "30000",
    "i_sAucResult": "",
    "i_sAucLane": "",
    "i_sEntryNo": "",
    "i_sParkingNo": "",
    "i_entryNoYn0": "ALL",
    "i_parkingNoYn0": "Y",
    "i_sAucNoTemp2": "1333@@2025-07-16@@AC202507090001",
    "i_sohYn": "ALL",
    "entrySort": "entry",
    "i_iPageSize": "10",
}

response = requests.post(
    "https://www.autohubauction.co.kr/newfront/receive/rc/receive_rc_list.do",
    cookies=cookies,
    headers=headers,
    data=data,
)
