"""Regression tests for the transparent Encar proxy routes.

Context: on 2026-07-15 commit 1888b6a made the shared proxy pool fail closed.
/api/catalog and /api/nav called get_proxy_pool() with no fallback, so both
returned 502 "proxy configuration unavailable" in production for days — while
/api/v1/encar/catalog, which hits the identical upstream URL through the
USE_PROXY gate, kept serving 200s. These tests pin the corrected behaviour.
"""

from __future__ import annotations

import asyncio
import base64
from urllib.parse import quote

import aiohttp
import pytest
import yarl
from fastapi import FastAPI
from fastapi.testclient import TestClient
from multidict import CIMultiDict, CIMultiDictProxy

from app.core.egress_breaker import EgressBreaker
from app.core.http_client import AsyncHttpResponse
from app.core.proxy_config import ProxyConfigurationError
from app.routes import encar_proxy


PROXY_ENV = (
    "AUCTION_PROXY_HOST",
    "AUCTION_PROXY_USERNAME",
    "AUCTION_PROXY_PASSWORD",
)
FAILOVER_ENV = (
    "ENCAR_PROXY_FAILOVER",
    "ENCAR_DIRECT_BLOCK_COOLDOWN_SECONDS",
    "RENDER_GIT_COMMIT",
)
UPSTREAM_BODY = '{"Count":214592,"SearchResults":[]}'
NAV_QUERY = "(And.Hidden.N._.CarType.A._.SellType.일반.)"

# What api.encar.com's CloudFront edge has answered Render since 2026-08-29.
CLOUDFRONT_HTML = (
    "<html><head><title>ERROR: The request could not be satisfied</title></head>"
    "<body><h1>403 ERROR</h1><h2>The request could not be satisfied.</h2>"
    "<p>Request blocked. We can't connect to the server for this app or "
    "website at this time.</p><hr><p>Generated by cloudfront (CloudFront)</p>"
    "</body></html>"
)
CLOUDFRONT_HEADERS = {"Server": "CloudFront", "Content-Type": "text/html"}
CLOUDFRONT_403 = (403, CLOUDFRONT_HTML, CLOUDFRONT_HEADERS)
OK_200 = (200, UPSTREAM_BODY, {})


def _reset_module_state() -> None:
    encar_proxy._client = None
    encar_proxy._breaker = None
    encar_proxy._NAV_CACHE.clear()
    encar_proxy._CATALOG_CACHE.clear()


@pytest.fixture(autouse=True)
def _reset_client(monkeypatch: pytest.MonkeyPatch):
    """Drop the module-level client, breaker, caches and env between tests."""
    _reset_module_state()
    for name in (*PROXY_ENV, "USE_PROXY", *FAILOVER_ENV):
        monkeypatch.delenv(name, raising=False)
    yield
    _reset_module_state()


@pytest.fixture
def client() -> TestClient:
    """Mount only the router under test.

    Importing main would construct several module-level service singletons,
    which is both slow and unrelated to this contract.
    """
    app = FastAPI()
    app.include_router(encar_proxy.router)
    return TestClient(app)


def _stub_get(monkeypatch: pytest.MonkeyPatch, *, status: int = 200, body: str = UPSTREAM_BODY):
    """Replace AsyncHttpClient.get with a recording stub."""
    calls: list[str] = []

    async def fake_get(
        self, url, headers=None, cookies=None, params=None, timeout=None, egress="auto", **kwargs
    ):
        calls.append(url)
        return AsyncHttpResponse(
            status_code=status, text=body, headers={}, url=url
        )

    monkeypatch.setattr("app.core.http_client.AsyncHttpClient.get", fake_get)
    return calls


def _raw_get(client: TestClient, path: str, **query: str):
    """Send `query` as a hand percent-encoded query string.

    Percent-encodes every value the way a browser's `encodeURIComponent`
    (and therefore the real frontend) would, so `+`/`&`/`#`/Korean all
    arrive as `%XX` on the wire. Starlette decodes them before the route
    sees `q`/`sr`/`inav`, exactly like a real request — this bypasses only
    httpx's own query encoder, whose choices are unrelated to what we're
    testing here.
    """
    qs = "&".join(f"{key}={quote(value, safe='')}" for key, value in query.items())
    return client.get(f"{path}?{qs}")


def _stub_raise(monkeypatch: pytest.MonkeyPatch, exc: BaseException):
    """Replace AsyncHttpClient.get with a stub that raises `exc`."""

    async def fake_get(
        self, url, headers=None, cookies=None, params=None, timeout=None, egress="auto", **kwargs
    ):
        raise exc

    monkeypatch.setattr("app.core.http_client.AsyncHttpClient.get", fake_get)


def _arm_failover(monkeypatch: pytest.MonkeyPatch) -> None:
    """Production shape: pool credentials present, USE_PROXY gate off."""
    monkeypatch.setenv("AUCTION_PROXY_HOST", "proxy.example.test:8080")
    monkeypatch.setenv("AUCTION_PROXY_USERNAME", "operator")
    monkeypatch.setenv("AUCTION_PROXY_PASSWORD", "secret")
    monkeypatch.setenv("USE_PROXY", "false")


def _stub_by_egress(monkeypatch: pytest.MonkeyPatch, *, direct, proxy) -> list[str]:
    """Answer each egress leg with `(status, body, headers)` or raise an exception.

    Returns the sequence of `egress` values the route asked for. A leg the
    route never names ("auto") is a KeyError on purpose: the whole fix is
    that the route chooses the leg explicitly.
    """
    outcomes = {"direct": direct, "proxy": proxy}
    seen: list[str] = []

    async def fake_get(
        self, url, headers=None, cookies=None, params=None, timeout=None, egress="auto", **kwargs
    ):
        seen.append(egress)
        outcome = outcomes[egress]
        if isinstance(outcome, BaseException):
            raise outcome
        status, body, response_headers = outcome
        return AsyncHttpResponse(
            status_code=status, text=body, headers=dict(response_headers), url=url
        )

    monkeypatch.setattr("app.core.http_client.AsyncHttpClient.get", fake_get)
    return seen


class FakeClock:
    def __init__(self, start: float = 1000.0) -> None:
        self.now = start

    def __call__(self) -> float:
        return self.now

    def advance(self, seconds: float) -> None:
        self.now += seconds


# --- The outage regression -------------------------------------------------


def test_catalog_serves_200_when_proxy_unconfigured(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    """THE regression test: no proxy credentials must not break Encar.

    Encar is proxy-OPTIONAL. Before the fix this returned
    502 {"error":"upstream_error","detail":"proxy configuration unavailable"}.
    """
    _stub_get(monkeypatch)

    response = client.get("/api/catalog", params={"sr": "|ModifiedDate|0|1"})

    assert response.status_code == 200
    assert response.text == UPSTREAM_BODY
    assert encar_proxy.get_encar_proxy_client().egress_mode == "direct"


def test_nav_serves_200_when_proxy_unconfigured(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    _stub_get(monkeypatch)

    response = client.get("/api/nav", params={"q": NAV_QUERY})

    assert response.status_code == 200
    assert response.text == UPSTREAM_BODY


def test_upstream_url_keeps_raw_korean_and_pipes(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Encar rejects a percent-encoded query; double-encoding yields Count: 0."""
    calls = _stub_get(monkeypatch)

    client.get("/api/nav", params={"q": NAV_QUERY, "inav": "|Metadata|Sort"})

    assert len(calls) == 1
    assert "일반" in calls[0], "Korean must not be percent-encoded"
    assert "|Metadata|Sort" in calls[0], "pipes must not be percent-encoded"
    assert "%EC%9D%BC%EB%B0%98" not in calls[0]


# --- `+`/`&`/`#` escaping (encar_query.encode_encar_query_param) -----------
#
# The frontend sends `+`, `&` and `#` as %2B/%26/%23 (encodeURIComponent).
# Starlette decodes them before the route sees `q`/`sr`/`inav`, so a raw `+`
# reaches this handler. Without re-escaping, that `+` goes out to Encar
# unchanged and is read as a space — see app/core/encar_query.py.


def test_catalog_plus_in_q_reaches_upstream_as_percent_2b(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    calls = _stub_get(monkeypatch)
    q = "(And.Hidden.N._.CarType.A._.SellType.일반._.FuelType.가솔린+전기.)"

    _raw_get(client, "/api/catalog", q=q, sr="|ModifiedDate|0|20")

    assert len(calls) == 1
    assert "FuelType.가솔린%2B전기." in calls[0]
    assert "+" not in calls[0].split("?", 1)[1], "no raw + must reach Encar"
    assert "일반" in calls[0], "Korean stays raw, as today"


def test_nav_plus_in_q_reaches_upstream_as_percent_2b(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    calls = _stub_get(monkeypatch)
    q = (
        "(And.Hidden.N._.SellType.일반._.(C.CarType.A._.(C.Manufacturer.현대._."
        "(C.ModelGroup.그랜저._.(C.Model.그랜저 하이브리드 (GN7_)._."
        "BadgeGroup.가솔린+전기 1600cc.))))))"
    )

    _raw_get(client, "/api/nav", q=q, inav="|Metadata|Sort")

    assert len(calls) == 1
    assert "BadgeGroup.가솔린%2B전기 1600cc." in calls[0]
    assert "+" not in calls[0].split("?", 1)[1]


def test_ampersand_and_hash_cannot_inject_params(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Security value: a keyword containing `&`/`#` must not smuggle a new
    query parameter (for example `&sr=|…|0|5000`)."""
    calls = _stub_get(monkeypatch)
    q = "(And.Search.keyword(a&count=false#x).)"

    _raw_get(client, "/api/catalog", q=q, sr="|ModifiedDate|0|20")

    assert len(calls) == 1
    parsed = yarl.URL(calls[0])
    assert set(parsed.query.keys()) == {"q", "sr", "count"}
    assert parsed.query["count"] == "true"
    assert parsed.query["q"] == q


def test_sr_and_inav_are_escaped(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    calls = _stub_get(monkeypatch)
    sr = "|ModifiedDate|0|20&count=false"

    _raw_get(client, "/api/catalog", q=NAV_QUERY, sr=sr)

    catalog_parsed = yarl.URL(calls[-1])
    assert set(catalog_parsed.query.keys()) == {"q", "sr", "count"}
    assert catalog_parsed.query["sr"] == sr

    inav = "|Metadata#x|Sort"
    _raw_get(client, "/api/nav", q=NAV_QUERY, inav=inav)

    nav_parsed = yarl.URL(calls[-1])
    assert set(nav_parsed.query.keys()) == {"q", "inav", "count"}
    assert nav_parsed.query["inav"] == inav


def test_nav_gets_no_sr_parameter(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Contract override: the nav URL never carries `sr`."""
    calls = _stub_get(monkeypatch)

    _raw_get(client, "/api/nav", q=NAV_QUERY, inav="|Metadata|Sort")

    assert len(calls) == 1
    assert "sr" not in yarl.URL(calls[0]).query


def test_nav_cache_constants_are_192_and_60() -> None:
    """Pins the maxsize/TTL raise so a future edit doesn't silently drop it."""
    assert encar_proxy.NAV_CACHE_MAXSIZE == 192
    assert encar_proxy.NAV_CACHE_FRESH_TTL_SECONDS == 60
    assert encar_proxy._NAV_CACHE._maxsize == 192
    assert encar_proxy._NAV_CACHE._ttl == 60


# --- Egress policy ---------------------------------------------------------


def test_gate_off_ignores_configured_proxy(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    """USE_PROXY=false keeps Encar off metered proxy bandwidth."""
    for name in PROXY_ENV:
        monkeypatch.setenv(name, "configured")
    monkeypatch.setenv("USE_PROXY", "false")
    _stub_get(monkeypatch)

    client.get("/api/catalog")

    assert encar_proxy.get_encar_proxy_client().egress_mode == "direct"


def test_gate_on_with_credentials_uses_proxy(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setenv("AUCTION_PROXY_HOST", "proxy.example.test:8080")
    monkeypatch.setenv("AUCTION_PROXY_USERNAME", "operator")
    monkeypatch.setenv("AUCTION_PROXY_PASSWORD", "secret")
    monkeypatch.setenv("USE_PROXY", "true")
    _stub_get(monkeypatch)

    client.get("/api/catalog")

    assert encar_proxy.get_encar_proxy_client().egress_mode == "proxy"


def test_client_is_reused_across_requests(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    """One pooled client per process — not a fresh session per request."""
    _stub_get(monkeypatch)

    for _ in range(5):
        client.get("/api/catalog")

    assert encar_proxy.get_encar_proxy_client() is encar_proxy.get_encar_proxy_client()


# --- Error differentiation -------------------------------------------------


def test_timeout_returns_504(client: TestClient, monkeypatch: pytest.MonkeyPatch) -> None:
    _stub_raise(monkeypatch, asyncio.TimeoutError())

    response = client.get("/api/catalog")

    assert response.status_code == 504
    assert response.json()["detail"]["code"] == "upstream_timeout"
    assert response.json()["detail"]["retryable"] is True


def test_proxy_connect_failure_returns_502_proxy_error(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    exc = aiohttp.ClientProxyConnectionError(None, OSError("refused"))
    _stub_raise(monkeypatch, exc)

    response = client.get("/api/catalog")

    assert response.status_code == 502
    assert response.json()["detail"]["code"] == "proxy_error"


def test_payload_error_returns_502_invalid_response(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    _stub_raise(monkeypatch, aiohttp.ClientPayloadError("truncated"))

    response = client.get("/api/catalog")

    assert response.status_code == 502
    assert response.json()["detail"]["code"] == "upstream_invalid_response"


def test_proxy_config_error_returns_503(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    _stub_raise(monkeypatch, ProxyConfigurationError("proxy configuration unavailable"))

    response = client.get("/api/catalog")

    assert response.status_code == 503
    assert response.json()["detail"]["code"] == "proxy_unavailable"
    assert response.json()["detail"]["retryable"] is False


def test_upstream_500_maps_to_502_with_upstream_status(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    """An Encar 5xx must be distinguishable from our own 502."""
    _stub_get(monkeypatch, status=500, body="upstream exploded")

    response = client.get("/api/catalog")

    assert response.status_code == 502
    assert response.json()["detail"]["code"] == "upstream_error"
    assert response.json()["detail"]["upstream_status"] == 500


def test_upstream_404_passes_through(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Encar's own 4xx semantics stay intact for the frontend."""
    _stub_get(monkeypatch, status=404, body='{"message":"not found"}')

    response = client.get("/api/catalog")

    assert response.status_code == 404
    assert response.text == '{"message":"not found"}'


def test_error_body_never_leaks_proxy_credentials(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    """A malformed AUCTION_PROXY_HOST must not publish the password.

    proxy_config.ProxyEntry.build_url does not validate `host` (contrast
    glovis_transport.py, which rejects / @ ? #), so a bad port yields an
    aiohttp.InvalidURL whose str() is the full proxy URL including the
    password. The previous handler serialized str(exc) straight into this
    public, unauthenticated response.
    """
    leaky = aiohttp.InvalidURL("http://operator:sup3rsecret@proxy.example.test:not_a_port")
    _stub_raise(monkeypatch, leaky)

    response = client.get("/api/catalog")

    assert response.status_code == 502
    assert b"sup3rsecret" not in response.content
    assert b"proxy.example.test" not in response.content
    assert b"operator" not in response.content


# ═══ The 2026-08-29 outage: CloudFront blocks Render's egress ═══════════════
#
# api.encar.com's edge answers every direct request from Render with 403
# "Request blocked" HTML. Before the fix _forward relayed that HTML verbatim as
# application/json and the catalog died. The Korean residential pool in
# AUCTION_PROXY_* was configured the whole time; these tests pin that the route
# now uses it — automatically, per request, with a cooldown, and only for Encar.


def test_direct_403_trips_breaker_and_retries_via_proxy(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    _arm_failover(monkeypatch)
    legs = _stub_by_egress(monkeypatch, direct=CLOUDFRONT_403, proxy=OK_200)

    response = client.get("/api/catalog")

    assert response.status_code == 200
    assert response.text == UPSTREAM_BODY
    assert legs == ["direct", "proxy"]
    assert encar_proxy.get_encar_breaker().is_open() is True
    assert response.headers["x-encar-source"] == "proxy"


def test_open_breaker_goes_proxy_first(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Inside the cooldown the direct leg is not even attempted."""
    _arm_failover(monkeypatch)
    encar_proxy.get_encar_breaker().trip()
    legs = _stub_by_egress(monkeypatch, direct=CLOUDFRONT_403, proxy=OK_200)

    response = client.get("/api/catalog")

    assert response.status_code == 200
    assert legs == ["proxy"]
    assert response.headers["x-encar-source"] == "proxy"


def test_proxy_also_blocked_returns_503_upstream_blocked(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Both legs refused: a structured, retryable 503 — never CloudFront's HTML."""
    _arm_failover(monkeypatch)
    legs = _stub_by_egress(monkeypatch, direct=CLOUDFRONT_403, proxy=CLOUDFRONT_403)

    response = client.get("/api/catalog")

    assert response.status_code == 503
    body = response.json()
    assert body["error"] == "upstream_blocked"
    assert body["detail"]["code"] == "upstream_blocked"
    assert body["detail"]["retryable"] is True
    assert body["detail"]["upstream_status"] == 403
    assert int(response.headers["retry-after"]) >= 1
    assert response.headers["content-type"].startswith("application/json")
    assert response.headers["cache-control"] == "no-store"
    assert b"cloudfront" not in response.content.lower()
    assert legs == ["direct", "proxy"]


def test_403_without_failover_credentials_is_structured_not_html(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    """No pool to fall over to: still no HTML masquerading as JSON."""
    legs = _stub_by_egress(monkeypatch, direct=CLOUDFRONT_403, proxy=OK_200)

    response = client.get("/api/catalog")

    assert response.status_code == 503
    assert response.json()["detail"]["code"] == "upstream_blocked"
    assert response.headers["content-type"].startswith("application/json")
    assert b"cloudfront" not in response.content.lower()
    assert legs == ["direct"], "unarmed: the proxy leg must never be requested"
    assert encar_proxy.get_encar_proxy_client().failover_armed is False


def test_kill_switch_disables_failover(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    _arm_failover(monkeypatch)
    monkeypatch.setenv("ENCAR_PROXY_FAILOVER", "false")
    legs = _stub_by_egress(monkeypatch, direct=CLOUDFRONT_403, proxy=OK_200)

    response = client.get("/api/catalog")

    assert response.status_code == 503
    assert response.json()["detail"]["code"] == "upstream_blocked"
    assert legs == ["direct"]
    assert encar_proxy.get_encar_proxy_client().failover_armed is False


def test_kill_switch_typo_keeps_failover_on(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Only an explicit falsey value may switch the fallback off."""
    _arm_failover(monkeypatch)
    monkeypatch.setenv("ENCAR_PROXY_FAILOVER", "flase")
    legs = _stub_by_egress(monkeypatch, direct=CLOUDFRONT_403, proxy=OK_200)

    response = client.get("/api/catalog")

    assert response.status_code == 200
    assert legs == ["direct", "proxy"]
    assert encar_proxy.get_encar_proxy_client().failover_armed is True


def test_cooldown_expiry_routes_direct_again_and_resets_on_success(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    _arm_failover(monkeypatch)
    clock = FakeClock()
    encar_proxy._breaker = EgressBreaker(600, clock=clock)
    legs = _stub_by_egress(monkeypatch, direct=CLOUDFRONT_403, proxy=OK_200)
    assert client.get("/api/catalog", params={"sr": "|ModifiedDate|0|21"}).status_code == 200
    assert legs == ["direct", "proxy"]

    clock.advance(601)
    infos: list[str] = []
    monkeypatch.setattr(encar_proxy.logger, "info", lambda m, *a, **k: infos.append(str(m)))
    legs = _stub_by_egress(monkeypatch, direct=OK_200, proxy=OK_200)
    # A different page: the first response is still in the catalog cache.
    response = client.get("/api/catalog", params={"sr": "|ModifiedDate|21|21"})

    assert response.status_code == 200
    assert legs == ["direct"]
    assert response.headers["x-encar-source"] == "direct"
    breaker = encar_proxy.get_encar_breaker()
    assert breaker.is_open() is False
    assert breaker.snapshot().trips == 1
    assert any("recovered" in m for m in infos), infos


def test_cooldown_expiry_reblock_retrips_and_falls_back_to_proxy(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    _arm_failover(monkeypatch)
    clock = FakeClock()
    encar_proxy._breaker = EgressBreaker(600, clock=clock)
    legs = _stub_by_egress(monkeypatch, direct=CLOUDFRONT_403, proxy=OK_200)
    assert client.get("/api/catalog", params={"sr": "|ModifiedDate|0|21"}).status_code == 200

    clock.advance(601)
    response = client.get("/api/catalog", params={"sr": "|ModifiedDate|21|21"})

    assert response.status_code == 200
    assert legs == ["direct", "proxy", "direct", "proxy"]
    breaker = encar_proxy.get_encar_breaker()
    assert breaker.is_open() is True
    assert breaker.snapshot().trips == 2


def test_block_warning_is_logged_once_per_trip(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Three blocked requests, one WARNING: the log must not scale with traffic."""
    warnings: list[str] = []
    monkeypatch.setattr(
        encar_proxy.logger, "warning", lambda m, *a, **k: warnings.append(str(m))
    )
    _arm_failover(monkeypatch)
    _stub_by_egress(monkeypatch, direct=CLOUDFRONT_403, proxy=OK_200)

    for page in range(3):
        response = client.get("/api/catalog", params={"sr": f"|ModifiedDate|{page * 21}|21"})
        assert response.status_code == 200

    assert len([m for m in warnings if "blocked" in m]) == 1


@pytest.mark.parametrize("cause", ["no_credentials", "kill_switch"])
def test_block_warning_when_unarmed_does_not_claim_proxy_routing(
    client: TestClient, monkeypatch: pytest.MonkeyPatch, cause: str
) -> None:
    """With nothing to fail over to, the WARNING must say so and name the fix."""
    if cause == "kill_switch":
        _arm_failover(monkeypatch)
        monkeypatch.setenv("ENCAR_PROXY_FAILOVER", "false")
    warnings: list[str] = []
    monkeypatch.setattr(
        encar_proxy.logger, "warning", lambda m, *a, **k: warnings.append(str(m))
    )
    _stub_by_egress(monkeypatch, direct=CLOUDFRONT_403, proxy=OK_200)

    assert client.get("/api/catalog").status_code == 503

    blocked = [m for m in warnings if "blocked" in m]
    assert len(blocked) == 1, warnings
    assert "via proxy" not in blocked[0]
    assert "AUCTION_PROXY_HOST" in blocked[0]
    assert "ENCAR_PROXY_FAILOVER" in blocked[0]


def test_proxy_transport_error_during_failover_returns_502_proxy_error(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    _arm_failover(monkeypatch)
    legs = _stub_by_egress(
        monkeypatch,
        direct=CLOUDFRONT_403,
        proxy=aiohttp.ClientProxyConnectionError(None, OSError("refused")),
    )

    response = client.get("/api/catalog")

    assert response.status_code == 502
    assert response.json()["detail"]["code"] == "proxy_error"
    assert legs == ["direct", "proxy"]
    assert encar_proxy.get_encar_breaker().is_open() is True


def test_timeout_on_direct_leg_does_not_failover(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    """A timeout is not a block: retrying through the proxy would double the wait."""
    _arm_failover(monkeypatch)
    legs = _stub_by_egress(monkeypatch, direct=asyncio.TimeoutError(), proxy=OK_200)

    response = client.get("/api/catalog")

    assert response.status_code == 504
    assert response.json()["detail"]["code"] == "upstream_timeout"
    assert legs == ["direct"]
    assert encar_proxy.get_encar_breaker().is_open() is False


def test_origin_500_does_not_trip_breaker(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    _arm_failover(monkeypatch)
    legs = _stub_by_egress(monkeypatch, direct=(500, '{"message":"boom"}', {}), proxy=OK_200)

    response = client.get("/api/catalog")

    assert response.status_code == 502
    assert response.json()["detail"]["code"] == "upstream_error"
    assert response.json()["detail"]["upstream_status"] == 500
    assert legs == ["direct"]
    assert encar_proxy.get_encar_breaker().is_open() is False


def test_cloudfront_503_html_counts_as_block(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    _arm_failover(monkeypatch)
    legs = _stub_by_egress(
        monkeypatch, direct=(503, CLOUDFRONT_HTML, CLOUDFRONT_HEADERS), proxy=OK_200
    )

    response = client.get("/api/catalog")

    assert response.status_code == 200
    assert legs == ["direct", "proxy"]
    breaker = encar_proxy.get_encar_breaker()
    assert breaker.is_open() is True
    assert breaker.snapshot().last_direct_status == 503
    assert breaker.snapshot().last_proxy_status == 200


def test_cloudfront_502_html_is_not_a_block(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    """CloudFront's own 502 page means Encar's origin is down for everyone."""
    _arm_failover(monkeypatch)
    legs = _stub_by_egress(
        monkeypatch, direct=(502, CLOUDFRONT_HTML, CLOUDFRONT_HEADERS), proxy=OK_200
    )

    response = client.get("/api/catalog")

    assert response.status_code == 502
    assert response.json()["detail"]["code"] == "upstream_error"
    assert response.json()["detail"]["upstream_status"] == 502
    assert legs == ["direct"]
    assert encar_proxy.get_encar_breaker().is_open() is False


def test_encar_api_base_and_headers_are_https(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    assert encar_proxy.ENCAR_API == "https://api.encar.com"
    assert encar_proxy._ENCAR_HEADERS["origin"] == "https://www.encar.com"
    assert encar_proxy._ENCAR_HEADERS["referer"] == "https://www.encar.com/"
    calls = _stub_get(monkeypatch)

    client.get("/api/catalog")

    assert calls[0].startswith("https://api.encar.com/search/car/list/premium?")


# ═══ The 2026-09-15 outage: Encar's edge answers Render with an empty 407 ═══
#
# Render's direct egress started receiving HTTP 407 with an empty body from
# api.encar.com (commit 92ab35d, failover armed, pool size 1). The breaker only
# recognised 403, so it never tripped, the proxy leg was never tried, and the
# raw 407 was relayed. Node's fetch treats any 407 as a network error, so
# Vercel surfaced "fetch failed" / 502 for every uncached filter combination.
# These tests pin that a 407 is a block on the direct leg and is never relayed
# on any leg.

SENTINEL_PROXY_HOST = "sentinel-proxy.example.test"
SENTINEL_PROXY_PORT = "8080"
SENTINEL_PROXY_USER = "sentinel-operator"
SENTINEL_PROXY_PASS = "sentinel-sup3rsecret"
SENTINEL_BASIC = base64.b64encode(
    f"{SENTINEL_PROXY_USER}:{SENTINEL_PROXY_PASS}".encode()
).decode()
EDGE_407 = (407, "", {"Content-Length": "0"})


def _arm_failover_with_sentinels(monkeypatch: pytest.MonkeyPatch) -> None:
    _arm_failover(monkeypatch)
    monkeypatch.setenv("AUCTION_PROXY_HOST", f"{SENTINEL_PROXY_HOST}:{SENTINEL_PROXY_PORT}")
    monkeypatch.setenv("AUCTION_PROXY_USERNAME", SENTINEL_PROXY_USER)
    monkeypatch.setenv("AUCTION_PROXY_PASSWORD", SENTINEL_PROXY_PASS)


def _capture_route_logs(monkeypatch: pytest.MonkeyPatch) -> list[str]:
    messages: list[str] = []
    for level in ("debug", "info", "warning", "error", "exception", "critical"):
        monkeypatch.setattr(
            encar_proxy.logger, level, lambda m, *a, **k: messages.append(str(m))
        )
    return messages


def _proxy_connect_407() -> aiohttp.ClientHttpProxyError:
    """What aiohttp raises when the proxy itself refuses our credentials.

    For an https:// target aiohttp opens a CONNECT tunnel, and a non-200
    CONNECT answer is raised as ClientHttpProxyError (connector.py) — it never
    comes back as a response. Its request_info carries the Proxy-Authorization
    header, so anything that echoed the exception would publish the password.
    """
    request_info = aiohttp.RequestInfo(
        url=yarl.URL("https://api.encar.com/search/car/list/premium"),
        method="CONNECT",
        headers=CIMultiDictProxy(
            CIMultiDict({"Proxy-Authorization": f"Basic {SENTINEL_BASIC}"})
        ),
        real_url=yarl.URL(
            f"http://{SENTINEL_PROXY_USER}:{SENTINEL_PROXY_PASS}@"
            f"{SENTINEL_PROXY_HOST}:{SENTINEL_PROXY_PORT}"
        ),
    )
    return aiohttp.ClientHttpProxyError(
        request_info,
        (),
        status=407,
        message=f"Proxy Authentication Required for {SENTINEL_PROXY_USER}",
        headers=CIMultiDictProxy(
            CIMultiDict({"Proxy-Authenticate": 'Basic realm="sentinel-realm"'})
        ),
    )


def _assert_no_proxy_secrets(*texts: str) -> None:
    for text in texts:
        for secret in (
            SENTINEL_PROXY_HOST,
            SENTINEL_PROXY_USER,
            SENTINEL_PROXY_PASS,
            SENTINEL_BASIC,
            "sentinel-realm",
        ):
            assert secret not in text, f"{secret!r} leaked into {text[:200]!r}"


def _assert_structured_error(response) -> dict:
    assert response.status_code != 407
    assert not 200 <= response.status_code < 300
    assert response.headers["content-type"].startswith("application/json")
    assert response.headers["cache-control"] == "no-store"
    body = response.json()
    assert body["error"] in encar_proxy._ERROR_STATUS
    assert body["detail"]["code"] == body["error"]
    assert response.status_code == encar_proxy._ERROR_STATUS[body["error"]]
    return body


@pytest.mark.parametrize(
    ("path", "params"),
    [
        ("/api/catalog", {}),
        ("/api/nav", {"q": NAV_QUERY}),
        ("/api/readside/vehicle/12345678", {}),
    ],
)
def test_direct_407_trips_breaker_and_retries_via_proxy(
    client: TestClient, monkeypatch: pytest.MonkeyPatch, path: str, params: dict
) -> None:
    """Mirrors test_direct_403_trips_breaker_and_retries_via_proxy for 407."""
    _arm_failover(monkeypatch)
    legs = _stub_by_egress(monkeypatch, direct=EDGE_407, proxy=OK_200)

    response = client.get(path, params=params)

    assert response.status_code == 200
    assert response.text == UPSTREAM_BODY
    assert legs == ["direct", "proxy"]
    assert response.headers["x-encar-source"] == "proxy"
    breaker = encar_proxy.get_encar_breaker()
    assert breaker.is_open() is True
    snapshot = breaker.snapshot()
    assert snapshot.trips == 1
    assert snapshot.last_direct_status == 407
    assert snapshot.last_proxy_status == 200

    # The trip is effective: the next (uncached) request skips direct.
    assert client.get("/api/readside/vehicle/87654321").status_code == 200
    assert legs == ["direct", "proxy", "proxy"]


def test_direct_407_and_proxy_407_is_structured_upstream_blocked(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Both legs answered 407 as a *response*: through a CONNECT tunnel that
    can only be Encar's edge refusing the proxy exit too — a double block."""
    _arm_failover_with_sentinels(monkeypatch)
    logs = _capture_route_logs(monkeypatch)
    legs = _stub_by_egress(monkeypatch, direct=EDGE_407, proxy=EDGE_407)

    response = client.get("/api/catalog")

    body = _assert_structured_error(response)
    assert response.status_code == 503
    assert body["error"] == "upstream_blocked"
    assert body["detail"]["retryable"] is True
    assert body["detail"]["upstream_status"] == 407
    assert int(response.headers["retry-after"]) >= 1
    assert legs == ["direct", "proxy"]
    diagnostics = encar_proxy.encar_diagnostics_snapshot()
    assert diagnostics.last_direct_status == 407
    assert diagnostics.last_proxy_status == 407
    assert diagnostics.breaker_open is True
    _assert_no_proxy_secrets(response.text, *logs)


def test_proxy_credentials_rejected_407_is_structured_proxy_error(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Bad or expired pool credentials: the proxy refuses CONNECT with 407."""
    _arm_failover_with_sentinels(monkeypatch)
    logs = _capture_route_logs(monkeypatch)
    legs = _stub_by_egress(monkeypatch, direct=EDGE_407, proxy=_proxy_connect_407())

    response = client.get("/api/catalog")

    body = _assert_structured_error(response)
    assert response.status_code == 502
    assert body["error"] == "proxy_error"
    assert body["detail"]["retryable"] is True
    assert legs == ["direct", "proxy"]
    diagnostics = encar_proxy.encar_diagnostics_snapshot()
    assert diagnostics.last_direct_status == 407
    assert diagnostics.last_proxy_status == 407, "diagnostics must show the proxy's 407"
    assert any("407" in m and "AUCTION_PROXY_PASSWORD" in m for m in logs), logs
    _assert_no_proxy_secrets(response.text, str(dict(response.headers)), *logs)


@pytest.mark.parametrize("cause", ["no_credentials", "kill_switch"])
def test_direct_407_without_failover_is_structured_503(
    client: TestClient, monkeypatch: pytest.MonkeyPatch, cause: str
) -> None:
    if cause == "kill_switch":
        _arm_failover(monkeypatch)
        monkeypatch.setenv("ENCAR_PROXY_FAILOVER", "false")
    legs = _stub_by_egress(monkeypatch, direct=EDGE_407, proxy=OK_200)

    response = client.get("/api/catalog")

    body = _assert_structured_error(response)
    assert response.status_code == 503
    assert body["error"] == "upstream_blocked"
    assert body["detail"]["upstream_status"] == 407
    assert int(response.headers["retry-after"]) >= 1
    assert legs == ["direct"], "unarmed: the proxy leg must never be requested"
    assert encar_proxy.get_encar_proxy_client().failover_armed is False


@pytest.mark.parametrize(
    "scenario",
    [
        "breaker_open_proxy_407",
        "breaker_open_proxy_connect_407",
        "use_proxy_primary_407",
        "use_proxy_primary_connect_407",
        "nav_both_407",
        "readside_both_407",
    ],
)
def test_raw_407_is_never_relayed_on_any_leg(
    client: TestClient, monkeypatch: pytest.MonkeyPatch, scenario: str
) -> None:
    _arm_failover_with_sentinels(monkeypatch)
    logs = _capture_route_logs(monkeypatch)
    path, params = "/api/catalog", {}
    proxy_outcome = _proxy_connect_407() if scenario.endswith("connect_407") else EDGE_407
    if scenario.startswith("breaker_open"):
        encar_proxy.get_encar_breaker().trip()
        expected_legs = ["proxy"]
    elif scenario.startswith("use_proxy_primary"):
        monkeypatch.setenv("USE_PROXY", "true")
        expected_legs = ["proxy"]
    else:
        expected_legs = ["direct", "proxy"]
        if scenario == "nav_both_407":
            path, params = "/api/nav", {"q": NAV_QUERY}
        else:
            path = "/api/readside/vehicle/12345678"
    legs = _stub_by_egress(monkeypatch, direct=EDGE_407, proxy=proxy_outcome)

    response = client.get(path, params=params)

    body = _assert_structured_error(response)
    expected_code = "proxy_error" if scenario.endswith("connect_407") else "upstream_blocked"
    assert body["error"] == expected_code
    assert legs == expected_legs
    assert encar_proxy.get_encar_breaker().snapshot().last_proxy_status == 407
    _assert_no_proxy_secrets(response.text, *logs)


# ═══ Caching ═════════════════════════════════════════════════════════════════


def test_nav_is_served_from_cache_within_ttl(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    calls = _stub_get(monkeypatch)

    first = client.get("/api/nav", params={"q": NAV_QUERY})
    second = client.get("/api/nav", params={"q": NAV_QUERY})

    assert len(calls) == 1
    assert first.status_code == second.status_code == 200
    assert first.text == second.text == UPSTREAM_BODY
    assert first.headers["x-encar-source"] == "direct"
    assert second.headers["x-encar-source"] == "cache"


def test_catalog_cache_key_includes_sort_and_page(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    calls = _stub_get(monkeypatch)

    client.get("/api/catalog", params={"sr": "|ModifiedDate|0|21"})
    client.get("/api/catalog", params={"sr": "|ModifiedDate|21|21"})
    client.get("/api/catalog", params={"sr": "|Price|0|21"})
    client.get("/api/catalog", params={"sr": "|Price|0|21", "count": "false"})

    assert len(calls) == 4
    assert len(set(calls)) == 4


def test_non_2xx_is_never_cached(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    outcomes = [(404, '{"message":"not found"}'), (200, UPSTREAM_BODY)]
    calls: list[str] = []

    async def fake_get(
        self, url, headers=None, cookies=None, params=None, timeout=None, egress="auto", **kwargs
    ):
        calls.append(url)
        status, body = outcomes[len(calls) - 1]
        return AsyncHttpResponse(status_code=status, text=body, headers={}, url=url)

    monkeypatch.setattr("app.core.http_client.AsyncHttpClient.get", fake_get)

    first = client.get("/api/nav", params={"q": NAV_QUERY})
    second = client.get("/api/nav", params={"q": NAV_QUERY})

    assert first.status_code == 404
    assert second.status_code == 200
    assert len(calls) == 2


def test_stale_nav_keeps_serving_during_block(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Facets change slowly; a block must not blank the filter sidebar."""
    calls = _stub_get(monkeypatch)
    with client:
        first = client.get("/api/nav", params={"q": NAV_QUERY})
        assert first.status_code == 200 and len(calls) == 1

        # Age the entry past its TTL but inside the stale window. The cache
        # keeps monotonic deadlines and has no clock hook, so reach in.
        encar_proxy._NAV_CACHE._entries[calls[0]].fresh_until = 0.0
        _stub_by_egress(monkeypatch, direct=CLOUDFRONT_403, proxy=CLOUDFRONT_403)

        second = client.get("/api/nav", params={"q": NAV_QUERY})
        # One more round trip on the same loop so the background refresh
        # scheduled by the stale hit has run before we look at its effects.
        client.get("/definitely-not-a-route")

    assert second.status_code == 200
    assert second.text == UPSTREAM_BODY
    assert second.headers["x-encar-source"] == "cache"
    assert encar_proxy._NAV_CACHE.stats()["inflight"] == 0
    assert encar_proxy.get_encar_breaker().is_open() is True, "the refresh saw the block"


# ═══ Readside passthrough ════════════════════════════════════════════════════
#
# Encar's edge refuses Vercel's addresses too, so the frontend detail page can
# no longer call api.encar.com/v1/readside itself. These routes are the
# allowlist: three fixed paths, one validated id, one validated plate.


def test_readside_vehicle_forwards_to_https_readside_path(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    body = '{"vehicleId":12345678,"category":{"manufacturerName":"현대"}}'
    calls = _stub_get(monkeypatch, body=body)

    response = client.get("/api/readside/vehicle/12345678")

    assert response.status_code == 200
    assert response.text == body
    assert response.headers["content-type"].startswith("application/json")
    assert calls == ["https://api.encar.com/v1/readside/vehicle/12345678"]


def test_readside_inspection_forwards(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    calls = _stub_get(monkeypatch, body='{"master":{"accdient":false}}')

    response = client.get("/api/readside/inspection/vehicle/12345678")

    assert response.status_code == 200
    assert calls == ["https://api.encar.com/v1/readside/inspection/vehicle/12345678"]


def test_readside_record_percent_encodes_vehicle_no(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    calls = _stub_get(monkeypatch, body='{"accidentCnt":0}')

    response = client.get(
        "/api/readside/record/vehicle/12345678/open", params={"vehicleNo": "12가3456"}
    )

    assert response.status_code == 200
    assert len(calls) == 1
    assert calls[0].endswith("/v1/readside/record/vehicle/12345678/open?vehicleNo=12%EA%B0%803456")
    assert calls[0].startswith("https://api.encar.com/")


@pytest.mark.parametrize(
    "path",
    [
        "/api/readside/vehicle/{id}",
        "/api/readside/inspection/vehicle/{id}",
        "/api/readside/record/vehicle/{id}/open?vehicleNo=12가3456",
    ],
)
@pytest.mark.parametrize("vehicle_id", ["abc", "12a", "..", "", "1" * 13, "１２３"])
def test_readside_rejects_invalid_vehicle_id(
    client: TestClient, monkeypatch: pytest.MonkeyPatch, path: str, vehicle_id: str
) -> None:
    """Validated before any network call — an allowlist, not a relay."""
    calls = _stub_get(monkeypatch)

    response = client.get(path.replace("{id}", vehicle_id))

    assert calls == [], "an invalid id must never reach api.encar.com"
    assert not 200 <= response.status_code < 300
    if vehicle_id not in ("", ".."):
        # "" and ".." may be refused by the router itself before the handler
        # runs; every other case must be the structured 400.
        assert response.status_code == 400
        assert response.json()["error"] == "invalid_vehicle_id"
        assert response.json()["detail"]["retryable"] is False


@pytest.mark.parametrize("vehicle_no", [None, "", "a" * 17, "12<3456", "12가3456;x"])
def test_readside_rejects_invalid_vehicle_no(
    client: TestClient, monkeypatch: pytest.MonkeyPatch, vehicle_no: str | None
) -> None:
    """None = the parameter is omitted entirely: still the structured 400,
    not FastAPI's 422, because the frontend contract lists only 400."""
    calls = _stub_get(monkeypatch)
    params = {} if vehicle_no is None else {"vehicleNo": vehicle_no}

    response = client.get("/api/readside/record/vehicle/12345678/open", params=params)

    assert calls == []
    assert response.status_code == 400
    assert response.json()["error"] == "invalid_vehicle_no"
    assert response.json()["detail"]["retryable"] is False


def test_readside_404_passes_through_as_json(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    """A removed car is Encar's 404, relayed so the frontend can notFound()."""
    _stub_get(monkeypatch, status=404, body='{"message":"Not Found"}')

    response = client.get("/api/readside/vehicle/12345678")

    assert response.status_code == 404
    assert response.text == '{"message":"Not Found"}'
    assert response.headers["content-type"].startswith("application/json")


def test_readside_403_fails_over_like_catalog(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    _arm_failover(monkeypatch)
    legs = _stub_by_egress(monkeypatch, direct=CLOUDFRONT_403, proxy=OK_200)

    response = client.get("/api/readside/vehicle/12345678")

    assert response.status_code == 200
    assert legs == ["direct", "proxy"]
    assert response.headers["x-encar-source"] == "proxy"


def test_readside_is_never_cached(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    calls = _stub_get(monkeypatch)

    first = client.get("/api/readside/vehicle/12345678")
    second = client.get("/api/readside/vehicle/12345678")

    assert len(calls) == 2
    assert first.headers["x-encar-source"] == "direct"
    assert second.headers["x-encar-source"] == "direct"
