"""GET /api/v1/diagnostics/encar — is the failover on, armed, and tripped?

During the 2026-08-29 outage the only evidence was a 403 HTML page relayed as
JSON. This route makes the egress state a one-request check: which leg is
primary, whether a proxy pool is held in reserve, whether the breaker is
open and since when, what each leg last answered, how the caches are doing,
and which commit is running. Names and numbers only — never a pool value.
"""

from __future__ import annotations

from datetime import datetime, timedelta

import pytest
from fastapi import FastAPI
from fastapi.testclient import TestClient

from app.core.http_client import AsyncHttpResponse
from app.routes import diagnostics, encar_proxy


PROXY_ENV = (
    "AUCTION_PROXY_HOST",
    "AUCTION_PROXY_USERNAME",
    "AUCTION_PROXY_PASSWORD",
)
FAILOVER_ENV = (
    "ENCAR_PROXY_FAILOVER",
    "ENCAR_DIRECT_BLOCK_COOLDOWN_SECONDS",
    "RENDER_GIT_COMMIT",
)
SENTINEL_HOST = "sentinel-proxy.example.test:8080"
SENTINEL_USER = "sentinel-operator"
SENTINEL_PASS = "sentinel-sup3rsecret"
CLOUDFRONT_HTML = "<html><body>Request blocked. Generated by cloudfront (CloudFront)</body></html>"
CACHE_STAT_KEYS = {"entries", "inflight", "hits", "stale_hits", "misses", "loads"}


def _reset_module_state() -> None:
    encar_proxy._client = None
    encar_proxy._breaker = None
    encar_proxy._NAV_CACHE.clear()
    encar_proxy._CATALOG_CACHE.clear()


@pytest.fixture(autouse=True)
def _reset(monkeypatch: pytest.MonkeyPatch):
    _reset_module_state()
    for name in (*PROXY_ENV, "USE_PROXY", *FAILOVER_ENV):
        monkeypatch.delenv(name, raising=False)
    yield
    _reset_module_state()


@pytest.fixture
def client() -> TestClient:
    app = FastAPI()
    app.include_router(diagnostics.router, prefix="/api/v1/diagnostics")
    app.include_router(encar_proxy.router)
    return TestClient(app)


def _arm_failover(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("AUCTION_PROXY_HOST", SENTINEL_HOST)
    monkeypatch.setenv("AUCTION_PROXY_USERNAME", SENTINEL_USER)
    monkeypatch.setenv("AUCTION_PROXY_PASSWORD", SENTINEL_PASS)
    monkeypatch.setenv("USE_PROXY", "false")


def _stub_direct_blocked_proxy_ok(monkeypatch: pytest.MonkeyPatch) -> None:
    async def fake_get(
        self, url, headers=None, cookies=None, params=None, timeout=None, egress="auto", **kwargs
    ):
        if egress == "direct":
            return AsyncHttpResponse(
                status_code=403, text=CLOUDFRONT_HTML, headers={"Server": "CloudFront"}, url=url
            )
        return AsyncHttpResponse(status_code=200, text='{"Count":1}', headers={}, url=url)

    monkeypatch.setattr("app.core.http_client.AsyncHttpClient.get", fake_get)


def test_encar_diagnostics_default_state(client: TestClient) -> None:
    response = client.get("/api/v1/diagnostics/encar")

    assert response.status_code == 200
    body = response.json()
    assert body["commit"] is None
    assert body["egress_mode"] == "direct"
    assert body["failover_enabled"] is True
    assert body["failover_armed"] is False
    assert body["proxy_pool_size"] == 0
    assert body["breaker_open"] is False
    assert body["breaker_seconds_remaining"] == 0
    assert body["breaker_trips"] == 0
    assert body["cooldown_seconds"] == 600
    assert body["last_direct_status"] is None
    assert body["last_proxy_status"] is None
    assert body["last_block_at"] is None
    assert set(body["caches"]) == {"nav", "catalog"}


def test_encar_diagnostics_reports_render_commit(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    sha = "0123abcd0123abcd0123abcd0123abcd0123abcd"
    monkeypatch.setenv("RENDER_GIT_COMMIT", sha)
    monkeypatch.setenv("ENCAR_DIRECT_BLOCK_COOLDOWN_SECONDS", "120")
    _arm_failover(monkeypatch)

    body = client.get("/api/v1/diagnostics/encar").json()

    assert body["commit"] == sha
    assert body["cooldown_seconds"] == 120
    assert body["failover_armed"] is True
    assert body["proxy_pool_size"] == 1


def test_encar_diagnostics_reflects_tripped_breaker(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    _arm_failover(monkeypatch)
    _stub_direct_blocked_proxy_ok(monkeypatch)
    assert client.get("/api/catalog").status_code == 200

    body = client.get("/api/v1/diagnostics/encar").json()

    assert body["breaker_open"] is True
    assert 0 < body["breaker_seconds_remaining"] <= 600
    assert body["breaker_trips"] == 1
    assert body["last_direct_status"] == 403
    assert body["last_proxy_status"] == 200
    blocked_at = datetime.fromisoformat(body["last_block_at"])
    assert blocked_at.utcoffset() == timedelta(0)
    assert abs((datetime.now(blocked_at.tzinfo) - blocked_at).total_seconds()) < 60


def test_encar_diagnostics_reports_cache_stats_keys(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    _arm_failover(monkeypatch)
    _stub_direct_blocked_proxy_ok(monkeypatch)
    client.get("/api/nav", params={"q": "(And.Hidden.N.)"})
    client.get("/api/nav", params={"q": "(And.Hidden.N.)"})

    body = client.get("/api/v1/diagnostics/encar").json()

    for name in ("nav", "catalog"):
        assert set(body["caches"][name]) == CACHE_STAT_KEYS, name
        assert all(isinstance(v, int) for v in body["caches"][name].values())
    assert body["caches"]["nav"]["entries"] == 1
    assert body["caches"]["nav"]["hits"] >= 1


def test_encar_diagnostics_never_contains_proxy_values(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    _arm_failover(monkeypatch)
    monkeypatch.setenv("AUCTION_PROXY_NAME", "sentinel-pool-name")
    _stub_direct_blocked_proxy_ok(monkeypatch)
    client.get("/api/catalog")

    response = client.get("/api/v1/diagnostics/encar")

    assert response.status_code == 200
    for secret in (SENTINEL_HOST, SENTINEL_USER, SENTINEL_PASS, "sentinel-pool-name"):
        assert secret not in response.text
