"""EgressBreaker: the state machine behind Encar's direct-then-proxy failover.

Since 2026-08-29 Encar's CloudFront edge answers Render's egress addresses with
HTTP 403 "Request blocked". The breaker remembers that the direct leg was
refused so the next requests skip straight to the Korean residential proxy
pool for one cooldown window, then quietly try direct again. It is a pure
in-memory object driven by an injected clock: nothing here touches the
network, the environment (except `cooldown_from_env`) or an event loop.
"""

from __future__ import annotations

from dataclasses import asdict
from datetime import datetime, timedelta, timezone

import pytest

from app.core import egress_breaker
from app.core.egress_breaker import (
    COOLDOWN_ENV,
    DEFAULT_COOLDOWN_SECONDS,
    BreakerSnapshot,
    EgressBreaker,
    cooldown_from_env,
    looks_like_edge_block,
)


CLOUDFRONT_HTML = (
    "<html><head><title>ERROR: The request could not be satisfied</title></head>"
    "<body><h1>403 ERROR</h1><h2>The request could not be satisfied.</h2>"
    "<p>Request blocked. We can't connect to the server for this app or "
    "website at this time.</p><hr><p>Generated by cloudfront (CloudFront)</p>"
    "</body></html>"
)


class FakeClock:
    """Deterministic stand-in for time.monotonic / time.time."""

    def __init__(self, start: float = 1000.0) -> None:
        self.now = start

    def __call__(self) -> float:
        return self.now

    def advance(self, seconds: float) -> None:
        self.now += seconds


# --- routing -----------------------------------------------------------------


def test_breaker_starts_closed_and_routes_direct_then_proxy() -> None:
    breaker = EgressBreaker(600, clock=FakeClock())

    assert breaker.cooldown_seconds == 600
    assert breaker.is_open() is False
    assert breaker.seconds_remaining() == 0
    assert breaker.legs(armed=True) == ("direct", "proxy")


def test_unarmed_breaker_only_ever_routes_direct() -> None:
    """No proxy credentials: there is nothing to fail over to, open or not."""
    breaker = EgressBreaker(600, clock=FakeClock())

    assert breaker.legs(armed=False) == ("direct",)
    breaker.trip()
    assert breaker.is_open() is True
    assert breaker.legs(armed=False) == ("direct",)


def test_trip_opens_and_routes_proxy_only() -> None:
    clock = FakeClock()
    breaker = EgressBreaker(600, clock=clock)

    assert breaker.trip() == "opened"

    assert breaker.is_open() is True
    assert breaker.legs(armed=True) == ("proxy",)
    assert breaker.seconds_remaining() == 600
    clock.advance(100)
    assert breaker.seconds_remaining() == 500


def test_trip_returns_opened_once_then_already_open() -> None:
    """Two concurrent 403s must produce one WARNING, not two."""
    breaker = EgressBreaker(600, clock=FakeClock())

    assert breaker.trip() == "opened"
    assert breaker.trip() == "already_open"
    assert breaker.trip() == "already_open"

    assert breaker.snapshot().trips == 1


def test_cooldown_expiry_reopens_direct_routing() -> None:
    """No half-open probe state: after the window the next request goes direct."""
    clock = FakeClock()
    breaker = EgressBreaker(600, clock=clock)
    breaker.trip()

    clock.advance(599.9)
    assert breaker.is_open() is True

    clock.advance(0.2)
    assert breaker.is_open() is False
    assert breaker.seconds_remaining() == 0
    assert breaker.legs(armed=True) == ("direct", "proxy")


def test_retrip_after_expiry_reports_opened_again() -> None:
    clock = FakeClock()
    breaker = EgressBreaker(600, clock=clock)
    assert breaker.trip() == "opened"

    clock.advance(601)
    assert breaker.trip() == "opened"

    assert breaker.is_open() is True
    assert breaker.seconds_remaining() == 600
    assert breaker.snapshot().trips == 2


def test_reset_closes_but_keeps_last_statuses() -> None:
    breaker = EgressBreaker(600, clock=FakeClock(), wall_clock=FakeClock(1_700_000_000.0))
    breaker.record("direct", 403)
    breaker.record("proxy", 200)
    breaker.trip()

    assert breaker.reset() is True, "closing an open breaker is a recovery"

    assert breaker.is_open() is False
    assert breaker.legs(armed=True) == ("direct", "proxy")
    snapshot = breaker.snapshot()
    assert snapshot.last_direct_status == 403
    assert snapshot.last_proxy_status == 200
    assert snapshot.last_block_at is not None
    assert snapshot.trips == 1
    assert breaker.reset() is False, "an already-closed breaker has nothing to recover"


def test_snapshot_is_iso_utc_and_numbers_only() -> None:
    blocked_at = datetime(2026, 9, 2, 8, 0, tzinfo=timezone.utc)
    clock = FakeClock()
    breaker = EgressBreaker(
        600, clock=clock, wall_clock=FakeClock(blocked_at.timestamp())
    )

    assert breaker.snapshot() == BreakerSnapshot(
        open=False,
        seconds_remaining=0.0,
        cooldown_seconds=600,
        trips=0,
        last_direct_status=None,
        last_proxy_status=None,
        last_block_at=None,
    )

    breaker.record("direct", 403)
    breaker.trip()
    clock.advance(60)
    snapshot = breaker.snapshot()

    assert snapshot.open is True
    assert snapshot.seconds_remaining == pytest.approx(540)
    assert snapshot.last_direct_status == 403
    parsed = datetime.fromisoformat(snapshot.last_block_at)
    assert parsed.utcoffset() == timedelta(0), "last_block_at must be UTC"
    assert parsed == blocked_at
    for name, value in asdict(snapshot).items():
        assert isinstance(value, (bool, int, float, str, type(None))), name


# --- cooldown configuration --------------------------------------------------


def test_cooldown_from_env_default(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.delenv(COOLDOWN_ENV, raising=False)
    assert cooldown_from_env() == DEFAULT_COOLDOWN_SECONDS == 600

    monkeypatch.setenv(COOLDOWN_ENV, "120")
    assert cooldown_from_env() == 120
    assert EgressBreaker.from_env().cooldown_seconds == 120


@pytest.mark.parametrize("raw", ["abc", "0", "-5", ""])
def test_cooldown_from_env_rejects_non_integer_and_non_positive(
    monkeypatch: pytest.MonkeyPatch, raw: str
) -> None:
    monkeypatch.setenv(COOLDOWN_ENV, raw)
    warnings: list[str] = []
    monkeypatch.setattr(
        egress_breaker.logger,
        "warning",
        lambda message, *a, **k: warnings.append(str(message)),
    )

    assert cooldown_from_env() == DEFAULT_COOLDOWN_SECONDS

    if raw:
        assert len(warnings) == 1 and COOLDOWN_ENV in warnings[0]
    else:
        assert warnings == [], "unset is the normal case and must not warn"


# --- edge-block detection ------------------------------------------------------


def test_403_is_a_block_regardless_of_body() -> None:
    assert looks_like_edge_block(403, {}, "") is True
    assert looks_like_edge_block(403, {"Content-Type": "application/json"}, '{"message":"forbidden"}') is True
    assert looks_like_edge_block(403, {"Server": "CloudFront"}, CLOUDFRONT_HTML) is True


def test_cloudfront_429_and_503_pages_are_blocks() -> None:
    assert looks_like_edge_block(429, {}, CLOUDFRONT_HTML) is True
    assert looks_like_edge_block(503, {}, CLOUDFRONT_HTML) is True
    # Case-insensitive, and only the first 4 KiB are inspected.
    assert looks_like_edge_block(429, {}, "GENERATED BY CLOUDFRONT") is True
    assert looks_like_edge_block(503, {}, "x" * 4096 + "generated by cloudfront") is False


def test_origin_json_404_500_and_cloudfront_502_are_not_blocks() -> None:
    assert looks_like_edge_block(404, {}, '{"message":"not found"}') is False
    assert looks_like_edge_block(500, {}, '{"message":"boom"}') is False
    assert looks_like_edge_block(429, {}, '{"message":"rate limited"}') is False
    assert looks_like_edge_block(503, {}, '{"message":"maintenance"}') is False
    # CloudFront's own 502/504 pages mean the origin is down, not that we are blocked.
    assert looks_like_edge_block(502, {"Server": "CloudFront"}, CLOUDFRONT_HTML) is False
    assert looks_like_edge_block(504, {"Server": "CloudFront"}, CLOUDFRONT_HTML) is False
    # x-cache is deliberately not a discriminator.
    assert looks_like_edge_block(200, {"x-cache": "Error from cloudfront"}, CLOUDFRONT_HTML) is False
