"""Direct-versus-proxy egress breaker for api.encar.com.

Since 2026-08-29 Encar's CloudFront edge answers Render's egress addresses with
HTTP 403 "Request blocked" (an HTML page signed "Generated by cloudfront").
The same URLs succeed from the Korean residential proxy pool, so the routes
in app/routes/encar_proxy.py try direct egress first and fall over to the
pool when the edge refuses them.

This module holds the two pieces that decision needs:

* :func:`looks_like_edge_block` — is this response the edge refusing *us*, as
  opposed to Encar's origin answering with its own 4xx/5xx JSON?
* :class:`EgressBreaker` — remembers that direct egress was refused so the
  next requests skip straight to the proxy for one cooldown window. There is
  deliberately no half-open probe state: when the window expires the next
  request simply goes direct-first again and re-trips if it is still blocked.

Nothing here reads the environment at import time or touches an event loop —
``start.sh`` runs ``gunicorn --preload``. :func:`cooldown_from_env` and
:meth:`EgressBreaker.from_env` read the environment when *called*.
"""

from __future__ import annotations

import os
import threading
import time
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Callable, Literal, Mapping

from app.core.logging import get_logger

logger = get_logger("egress_breaker")

Egress = Literal["direct", "proxy"]

DEFAULT_COOLDOWN_SECONDS = 600
COOLDOWN_ENV = "ENCAR_DIRECT_BLOCK_COOLDOWN_SECONDS"

# CloudFront stamps every page it generates itself with this footer. A 403 is
# a block regardless of body; for 429/503 the footer is what separates the
# edge refusing us from Encar's origin rate-limiting or being in maintenance.
_CLOUDFRONT_SIGNATURE = "generated by cloudfront"
_SIGNATURE_SCAN_BYTES = 4096


def cooldown_from_env() -> int:
    """Read the block cooldown, falling back to the default for unusable values.

    Names only the variable in the WARNING: the value is not a secret, but the
    startup log is the one place this project never echoes configuration.
    """
    raw = os.getenv(COOLDOWN_ENV, "")
    try:
        value = int(raw)
    except ValueError:
        value = 0
    if value > 0:
        return value
    if raw.strip():
        logger.warning(
            f"{COOLDOWN_ENV} is not a positive integer; using the default "
            f"{DEFAULT_COOLDOWN_SECONDS}s"
        )
    return DEFAULT_COOLDOWN_SECONDS


def looks_like_edge_block(status: int, headers: Mapping[str, str], text: str) -> bool:
    """Return True when the response is the CDN edge refusing this egress address.

    * ``403`` is a block whatever the body says: Encar's search API has no
      403 of its own, and the edge sometimes answers with an empty body.
    * ``429`` / ``503`` count only when the body carries CloudFront's own
      footer; the same statuses with JSON bodies are the origin talking.
    * Everything else — including CloudFront's 502/504 "origin unreachable"
      pages and any origin 4xx/5xx — is not a block.

    ``headers`` is accepted so callers can pass the whole response without
    picking fields; it is intentionally not consulted. ``x-cache: Error from
    cloudfront`` accompanies every CloudFront-generated page, block or not,
    so it cannot discriminate.
    """
    if status == 403:
        return True
    if status in (429, 503):
        return _CLOUDFRONT_SIGNATURE in text[:_SIGNATURE_SCAN_BYTES].lower()
    return False


@dataclass(frozen=True)
class BreakerSnapshot:
    """Read-only view for diagnostics. Numbers, booleans and ISO strings only."""

    open: bool
    seconds_remaining: float
    cooldown_seconds: int
    trips: int
    last_direct_status: int | None
    last_proxy_status: int | None
    last_block_at: str | None


class EgressBreaker:
    """Per-process memory of "direct egress is currently blocked".

    Thread-safe in the same style as ``ProxyPool``: gunicorn runs one event
    loop per worker, but the diagnostics route and the request path may still
    observe the breaker from different threads under the test client.

    Args:
        cooldown_seconds: How long, after a block, requests skip the direct leg.
        clock: Monotonic clock used for the cooldown window (injectable).
        wall_clock: Wall clock used only to timestamp ``last_block_at``.
    """

    def __init__(
        self,
        cooldown_seconds: int,
        *,
        clock: Callable[[], float] = time.monotonic,
        wall_clock: Callable[[], float] = time.time,
    ) -> None:
        if cooldown_seconds <= 0:
            raise ValueError("cooldown_seconds must be positive")
        self.cooldown_seconds = cooldown_seconds
        self._clock = clock
        self._wall_clock = wall_clock
        self._lock = threading.Lock()
        self._opened_at: float | None = None
        self._trips = 0
        self._last_direct_status: int | None = None
        self._last_proxy_status: int | None = None
        self._last_block_at: float | None = None

    @classmethod
    def from_env(cls) -> "EgressBreaker":
        """Build a breaker with the cooldown from ``ENCAR_DIRECT_BLOCK_COOLDOWN_SECONDS``."""
        return cls(cooldown_from_env())

    # ------------------------------------------------------------------
    # state queries
    # ------------------------------------------------------------------
    def _seconds_remaining_locked(self) -> float:
        if self._opened_at is None:
            return 0.0
        return max(0.0, self.cooldown_seconds - (self._clock() - self._opened_at))

    def is_open(self) -> bool:
        """True while the cooldown window started by the last trip is running."""
        with self._lock:
            return self._seconds_remaining_locked() > 0

    def seconds_remaining(self) -> float:
        """Seconds left in the cooldown window; 0 when closed or expired."""
        with self._lock:
            return self._seconds_remaining_locked()

    def legs(self, *, armed: bool) -> tuple[Egress, ...]:
        """Egress legs to try, in order, for one request.

        ``armed`` is whether a proxy pool exists to fail over to. Without one
        the only leg is direct — an open breaker changes nothing, because a
        403 answered honestly beats a proxy that does not exist.
        """
        if not armed:
            return ("direct",)
        if self.is_open():
            return ("proxy",)
        return ("direct", "proxy")

    # ------------------------------------------------------------------
    # state transitions
    # ------------------------------------------------------------------
    def record(self, egress: Egress, status: int) -> None:
        """Remember the last HTTP status seen on each leg (diagnostics only)."""
        with self._lock:
            if egress == "direct":
                self._last_direct_status = status
            else:
                self._last_proxy_status = status

    def trip(self) -> Literal["opened", "already_open"]:
        """Mark direct egress as blocked.

        Returns ``"opened"`` when this call started a cooldown window — the
        breaker was closed, or its previous window had expired — so the
        caller can log one WARNING per window rather than one per request.
        ``"already_open"`` only refreshes ``last_block_at``.
        """
        with self._lock:
            self._last_block_at = self._wall_clock()
            if self._seconds_remaining_locked() > 0:
                return "already_open"
            self._opened_at = self._clock()
            self._trips += 1
            return "opened"

    def reset(self) -> bool:
        """Close the breaker after direct egress succeeded.

        Returns True when there was an open or expired window to clear, so the
        caller can log the recovery exactly once; False is the steady state
        and must stay silent. ``last_*`` bookkeeping survives a reset.
        """
        with self._lock:
            recovered = self._opened_at is not None
            self._opened_at = None
            return recovered

    def snapshot(self) -> BreakerSnapshot:
        with self._lock:
            last_block_at = (
                datetime.fromtimestamp(self._last_block_at, tz=timezone.utc).isoformat(
                    timespec="seconds"
                )
                if self._last_block_at is not None
                else None
            )
            return BreakerSnapshot(
                open=self._seconds_remaining_locked() > 0,
                seconds_remaining=self._seconds_remaining_locked(),
                cooldown_seconds=self.cooldown_seconds,
                trips=self._trips,
                last_direct_status=self._last_direct_status,
                last_proxy_status=self._last_proxy_status,
                last_block_at=last_block_at,
            )
